/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExpensesImport } from './routes/expenses'
import { Route as IndexImport } from './routes/index'
import { Route as ReportsIndexImport } from './routes/reports/index'
import { Route as ExpensesIndexImport } from './routes/expenses/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ExpensesAddIndexImport } from './routes/expenses/add/index'

// Create/Update Routes

const ExpensesRoute = ExpensesImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReportsIndexRoute = ReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesIndexRoute = ExpensesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesAddIndexRoute = ExpensesAddIndexImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => ExpensesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexImport
      parentRoute: typeof ExpensesImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexImport
      parentRoute: typeof rootRoute
    }
    '/expenses/add/': {
      id: '/expenses/add/'
      path: '/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof ExpensesAddIndexImport
      parentRoute: typeof ExpensesImport
    }
  }
}

// Create and export the route tree

interface ExpensesRouteChildren {
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  ExpensesAddIndexRoute: typeof ExpensesAddIndexRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesIndexRoute: ExpensesIndexRoute,
  ExpensesAddIndexRoute: ExpensesAddIndexRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/expenses/add': typeof ExpensesAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/expenses/add': typeof ExpensesAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/expenses/add/': typeof ExpensesAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/dashboard'
    | '/expenses/'
    | '/reports'
    | '/expenses/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/expenses' | '/reports' | '/expenses/add'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/dashboard/'
    | '/expenses/'
    | '/reports/'
    | '/expenses/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/expenses",
        "/dashboard/",
        "/reports/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/expenses": {
      "filePath": "expenses.tsx",
      "children": [
        "/expenses/",
        "/expenses/add/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/expenses/": {
      "filePath": "expenses/index.tsx",
      "parent": "/expenses"
    },
    "/reports/": {
      "filePath": "reports/index.tsx"
    },
    "/expenses/add/": {
      "filePath": "expenses/add/index.tsx",
      "parent": "/expenses"
    }
  }
}
ROUTE_MANIFEST_END */
